/* This file was automatically generated by CasADi.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) sl_drone_constr_h_e_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s3[32] = {10, 9, 0, 5, 8, 9, 10, 11, 13, 15, 18, 20, 0, 1, 2, 3, 4, 2, 3, 4, 2, 3, 4, 0, 2, 1, 3, 0, 1, 4, 0, 1};
static const casadi_int casadi_s4[28] = {10, 10, 0, 4, 8, 10, 12, 15, 15, 15, 15, 15, 15, 0, 1, 2, 4, 0, 1, 3, 4, 0, 2, 1, 3, 0, 1, 4};
static const casadi_int casadi_s5[3] = {9, 0, 0};

/* sl_drone_constr_h_e_fun_jac_uxt_zt_hess:(i0[10],i1[],i2[9],i3[],i4[])->(o0[9],o1[10x9,20nz],o2[10x10,15nz],o3[9x0],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=2.4498411712345343e+00;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[0]? arg[0][0] : 0;
  a3=(a1+a2);
  a4=-4.0000000000000002e-01;
  a5=(a3-a4);
  a6=(a0*a5);
  a7=(a6*a5);
  a8=3.6100249311159209e+00;
  a9=arg[0]? arg[0][3] : 0;
  a10=arg[0]? arg[0][1] : 0;
  a11=(a9+a10);
  a12=1.5000000000000000e+00;
  a13=(a11-a12);
  a14=(a8*a13);
  a15=(a14*a13);
  a7=(a7+a15);
  a15=1.4536103098405859e+00;
  a16=arg[0]? arg[0][4] : 0;
  a17=1.;
  a18=casadi_sq(a2);
  a19=casadi_sq(a10);
  a18=(a18+a19);
  a18=(a17-a18);
  a18=sqrt(a18);
  a19=(a16+a18);
  a20=-6.9999999999999996e-01;
  a21=(a19-a20);
  a22=(a15*a21);
  a23=(a22*a21);
  a7=(a7+a23);
  if (res[0]!=0) res[0][0]=a7;
  a4=(a1-a4);
  a7=(a0*a4);
  a23=(a7*a4);
  a12=(a9-a12);
  a24=(a8*a12);
  a25=(a24*a12);
  a23=(a23+a25);
  a20=(a16-a20);
  a25=(a15*a20);
  a26=(a25*a20);
  a23=(a23+a26);
  if (res[0]!=0) res[0][1]=a23;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a9;
  if (res[0]!=0) res[0][4]=a16;
  if (res[0]!=0) res[0][5]=a3;
  if (res[0]!=0) res[0][6]=a11;
  if (res[0]!=0) res[0][7]=a19;
  a19=casadi_sq(a2);
  a11=casadi_sq(a10);
  a19=(a19+a11);
  if (res[0]!=0) res[0][8]=a19;
  a19=(a0*a5);
  a19=(a19+a6);
  a11=(a2/a18);
  a3=(a15*a11);
  a3=(a21*a3);
  a16=(a22*a11);
  a3=(a3+a16);
  a19=(a19-a3);
  if (res[1]!=0) res[1][0]=a19;
  a19=(a8*a13);
  a19=(a19+a14);
  a3=(a10/a18);
  a16=(a15*a3);
  a16=(a21*a16);
  a9=(a22*a3);
  a16=(a16+a9);
  a19=(a19-a16);
  if (res[1]!=0) res[1][1]=a19;
  a5=(a0*a5);
  a5=(a5+a6);
  if (res[1]!=0) res[1][2]=a5;
  a13=(a8*a13);
  a13=(a13+a14);
  if (res[1]!=0) res[1][3]=a13;
  a13=(a15*a21);
  a13=(a13+a22);
  if (res[1]!=0) res[1][4]=a13;
  a4=(a0*a4);
  a4=(a4+a7);
  if (res[1]!=0) res[1][5]=a4;
  a12=(a8*a12);
  a12=(a12+a24);
  if (res[1]!=0) res[1][6]=a12;
  a20=(a15*a20);
  a20=(a20+a25);
  if (res[1]!=0) res[1][7]=a20;
  if (res[1]!=0) res[1][8]=a17;
  if (res[1]!=0) res[1][9]=a17;
  if (res[1]!=0) res[1][10]=a17;
  if (res[1]!=0) res[1][11]=a17;
  if (res[1]!=0) res[1][12]=a17;
  if (res[1]!=0) res[1][13]=a17;
  if (res[1]!=0) res[1][14]=a17;
  a11=(-a11);
  if (res[1]!=0) res[1][15]=a11;
  a3=(-a3);
  if (res[1]!=0) res[1][16]=a3;
  if (res[1]!=0) res[1][17]=a17;
  a17=(a2+a2);
  if (res[1]!=0) res[1][18]=a17;
  a17=(a10+a10);
  if (res[1]!=0) res[1][19]=a17;
  a17=2.;
  a3=arg[2]? arg[2][8] : 0;
  a11=(a17*a3);
  a20=arg[2]? arg[2][7] : 0;
  a25=arg[2]? arg[2][0] : 0;
  a22=(a22*a25);
  a21=(a21*a25);
  a21=(a15*a21);
  a22=(a22+a21);
  a20=(a20+a22);
  a22=(a18+a18);
  a20=(a20/a22);
  a21=(a17*a20);
  a12=(a2+a2);
  a24=(a20/a22);
  a2=(a2/a18);
  a4=(a2+a2);
  a4=(a24*a4);
  a7=(a15*a2);
  a7=(a25*a7);
  a2=(a25*a2);
  a2=(a15*a2);
  a7=(a7+a2);
  a2=(a7/a22);
  a4=(a4-a2);
  a2=(a12*a4);
  a21=(a21+a2);
  a11=(a11-a21);
  a21=(a0*a25);
  a2=(a0*a25);
  a21=(a21+a2);
  a11=(a11+a21);
  if (res[2]!=0) res[2][0]=a11;
  a11=(a10+a10);
  a4=(a11*a4);
  a4=(-a4);
  if (res[2]!=0) res[2][1]=a4;
  if (res[2]!=0) res[2][2]=a21;
  a7=(-a7);
  if (res[2]!=0) res[2][3]=a7;
  a10=(a10/a18);
  a7=(a10+a10);
  a24=(a24*a7);
  a7=(a15*a10);
  a7=(a25*a7);
  a10=(a25*a10);
  a10=(a15*a10);
  a7=(a7+a10);
  a22=(a7/a22);
  a24=(a24-a22);
  a22=(a12*a24);
  a22=(-a22);
  if (res[2]!=0) res[2][4]=a22;
  a3=(a17*a3);
  a17=(a17*a20);
  a24=(a11*a24);
  a17=(a17+a24);
  a3=(a3-a17);
  a17=(a8*a25);
  a24=(a8*a25);
  a17=(a17+a24);
  a3=(a3+a17);
  if (res[2]!=0) res[2][5]=a3;
  if (res[2]!=0) res[2][6]=a17;
  a7=(-a7);
  if (res[2]!=0) res[2][7]=a7;
  a7=(a0*a25);
  a17=(a0*a25);
  a7=(a7+a17);
  if (res[2]!=0) res[2][8]=a7;
  a17=arg[2]? arg[2][1] : 0;
  a3=(a0*a17);
  a0=(a0*a17);
  a3=(a3+a0);
  a3=(a3+a7);
  if (res[2]!=0) res[2][9]=a3;
  a3=(a8*a25);
  a7=(a8*a25);
  a3=(a3+a7);
  if (res[2]!=0) res[2][10]=a3;
  a7=(a8*a17);
  a8=(a8*a17);
  a7=(a7+a8);
  a7=(a7+a3);
  if (res[2]!=0) res[2][11]=a7;
  a7=(a15*a25);
  a18=(a7/a18);
  a12=(a12*a18);
  a12=(-a12);
  if (res[2]!=0) res[2][12]=a12;
  a11=(a11*a18);
  a11=(-a11);
  if (res[2]!=0) res[2][13]=a11;
  a11=(a15*a17);
  a17=(a15*a17);
  a11=(a11+a17);
  a15=(a15*a25);
  a7=(a7+a15);
  a11=(a11+a7);
  if (res[2]!=0) res[2][14]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int sl_drone_constr_h_e_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int sl_drone_constr_h_e_fun_jac_uxt_zt_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int sl_drone_constr_h_e_fun_jac_uxt_zt_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sl_drone_constr_h_e_fun_jac_uxt_zt_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int sl_drone_constr_h_e_fun_jac_uxt_zt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void sl_drone_constr_h_e_fun_jac_uxt_zt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void sl_drone_constr_h_e_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void sl_drone_constr_h_e_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int sl_drone_constr_h_e_fun_jac_uxt_zt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int sl_drone_constr_h_e_fun_jac_uxt_zt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real sl_drone_constr_h_e_fun_jac_uxt_zt_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sl_drone_constr_h_e_fun_jac_uxt_zt_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* sl_drone_constr_h_e_fun_jac_uxt_zt_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sl_drone_constr_h_e_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* sl_drone_constr_h_e_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int sl_drone_constr_h_e_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
